[fix] dependency of description pkg.
CIR-KIT-Unit03/cirkit_unit03_common pull request #5
Opened 2016-11-13 14:31 UTC by MoriKen254

練習がてら`description`pkgの`package.xml`と`CMakelists.txt`を整理してみました．ご査収下さい．

2016-11-13 16:10 UTC, forno requested changes
launchファイルでの依存について触れてないように思います。
launchファイルでfindしている先のパッケージに対しては実行時依存するのが定番のようです。
- format 1 では<run_depend>
- format 2 では<exec_depend>

で実行時依存を表せますので、そのように修正をお願いいたします。

2016-11-13 16:12 UTC, forno commented
またmarkdownの記法にやられました。　一部修正しました。 怪しいところはバッククォートでコード化するほうがよいですね。
> - format 1 では `<run_depend>`
- format 2 では `<exec_depend>`

2016-11-14 13:53 UTC, MoriKen254 commented
レビューありがとうございます．後ほど対応します．

2016-11-14 22:32 UTC, MoriKen254 commented
\<exec_depend> を挿入しました．ついでにurlのタグも直しました．

2016-11-14 23:08 UTC, forno requested changes
もう少し具体的にレビュしてみました。

2016-11-14 23:08 UTC, forno commented on cirkit_unit03_description/package.xml
- joint_state_publisher
- robot_state_publisher
- rviz (この子だけmoveit!自動生成ファイルには依存がない)

の実行時依存が抜けているようです。

それからurdfが入っていたようなのでそちらの依存も足すべきかと思います。

2016-11-14 23:11 UTC, forno requested changes
よくみたら自己参照してました。

2016-11-14 23:11 UTC, forno commented on cirkit_unit03_description/package.xml
> +  <exec_depend>cirkit_unit03_description</exec_depend>
このパッケージがcirkit_unit03_descriptionです。
自分自身への依存は書かないものです。

2016-11-14 23:22 UTC, MoriKen254 commented on cirkit_unit03_description/package.xml
レビューありがとうございます．
直前の \<depend> タグに`urdf`を入れてありますが，\<exec_depend>としても追加したほうがよいですか？

2016-11-14 23:25 UTC, MoriKen254 commented on cirkit_unit03_description/package.xml
ビルドしていないから，`urdf`を入れるタグを /<depend> -> /<exec_depend> と変更したほうがよい，ということでしょうか．失礼しました^^;

2016-11-14 23:37 UTC, forno commented on cirkit_unit03_description/package.xml
あ。ごめんなさいまし。
ちゃんとurdfへのタグがあるのに、見逃していただけのようです。
これで大丈夫です。失礼しました。

2016-11-15 14:00 UTC, forno commented
`joint_state_publisher` と `robot_state_publisher`の実行時依存が追加されたらApproveします。

2016-11-15 14:40 UTC, MoriKen254 commented
実行時依存を追加しました．pkg名の誤りも見つけたので，合わせて修正しておきました．

2016-11-15 14:44 UTC, forno approved these changes

2016-11-15 14:45 UTC, forno commented
見逃していた依存も解決していただきありがとうございます。

2016-11-15 14:50 UTC, merged